Redux Middleware
wolox-training/cr-react-native pull request #10
Opened 2021-05-26 18:24 UTC by CristianRWolox

## Summary

- Add redux-thunk to the project.

## Trello Card
https://trello.com/c/6YxECpTs/28-n-92-redux-ii-middleware

2021-05-26 19:33 UTC, guidoprinc requested changes

2021-05-26 19:33 UTC, guidoprinc commented on wbooks/src/redux/book/actions.ts
> +    const response = { ok: true, data: BOOKS_MOCK, error: '' };
replace with a promise

2021-05-26 19:33 UTC, guidoprinc commented on wbooks/src/redux/book/actions.ts
> +        isFetching: false,
replace `isFetching` with `loading`

2021-05-27 00:59 UTC, CristianRWolox commented on wbooks/src/redux/book/actions.ts
> +    const response = { ok: true, data: BOOKS_MOCK, error: '' };
Done!

2021-05-27 00:59 UTC, CristianRWolox commented on wbooks/src/redux/book/actions.ts
> +        isFetching: false,
Done!

2021-05-27 03:51 UTC, guidoprinc approved these changes

2021-05-27 03:55 UTC, merged