Login redux
wolox-training/cr-react-native pull request #17
Opened 2021-05-27 22:21 UTC by CristianRWolox

## Summary
- Add action for authentication
- Add reducer for authentication
- Implement service to authenticate 

## Trello Card
https://trello.com/c/JlFoD0oE/33-n-103-funcionalidad-de-login-con-redux

2021-05-28 18:21 UTC, guidoprinc requested changes

2021-05-28 18:21 UTC, guidoprinc commented on wbooks/src/redux/auth/actions.ts
> +    target: 'user',
extract target as a constant outside `actionCreators`

2021-05-28 18:21 UTC, guidoprinc commented on wbooks/src/services/AuthService.ts
> +  Promise.resolve({ ok: true, data: { id: 1, toke: 'AE12OI45PK56LK', client: email }, problem: '' });
token

2021-05-31 11:56 UTC, mcolombo87 commented on wbooks/src/app/screens/Login/index.tsx
> +  const onSubmit = (data: DataForm) => {
extract email and password from data.

```suggestion
  const onSubmit = (data: DataForm) => {
```
```suggestion
  const onSubmit = ({ email, password }: DataForm) => {
```

2021-05-31 15:28 UTC, CristianRWolox commented on wbooks/src/services/AuthService.ts
> +  Promise.resolve({ ok: true, data: { id: 1, toke: 'AE12OI45PK56LK', client: email }, problem: '' });
Done!

2021-05-31 15:30 UTC, CristianRWolox commented on wbooks/src/redux/auth/actions.ts
> +    target: 'user',
Done!

2021-05-31 15:31 UTC, CristianRWolox commented on wbooks/src/app/screens/Login/index.tsx
> +  const onSubmit = (data: DataForm) => {
Done!

2021-05-31 17:24 UTC, guidoprinc approved these changes

2021-05-31 17:27 UTC, merged