Gradient
wolox-training/cr-react-native pull request #27
Opened 2021-06-03 13:30 UTC by CristianRWolox

## Summary

- Implement gradient to rent button

## Screenshots

[Change!] Show the screenshots of the views you modified.

### Android

#### Galaxy S (or similar)
![Screenshot_1622726544](https://user-images.githubusercontent.com/83975070/120651873-db3d9b00-c444-11eb-8edd-9035bdb788c9.png)

#### Pixel 2/3 (or similar)
![Screenshot_1622726540](https://user-images.githubusercontent.com/83975070/120651882-ded12200-c444-11eb-984c-93be2ca833a8.png)

#### Pixel 3XL (or similar)
![Screenshot_1622726403](https://user-images.githubusercontent.com/83975070/120651901-e264a900-c444-11eb-9284-7c2c0e1175c4.png)

### iOS

#### iPhone SE (or similar)
![simulator_screenshot_A3BE8211-4074-4B78-9A1E-16E0C0A525F7](https://user-images.githubusercontent.com/83975070/120652859-c8779600-c445-11eb-8466-fe91e4cc7210.png)

#### iPhone 6/7/8 (or similar)
![simulator_screenshot_C8BA4BFA-AD24-4BBF-A3D0-978B9F88FBFD](https://user-images.githubusercontent.com/83975070/120652773-b269d580-c445-11eb-8d62-5eba45bb1df0.png)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
![Simulator Screen Shot - iPhone 11 - 2021-06-03 at 08 26 59](https://user-images.githubusercontent.com/83975070/120652569-7f274680-c445-11eb-9aee-0c77265ceb3e.png)

## Trello Card

[Gradient](https://trello.com/c/hu9MxI6t/38-n-14-gradiente)

2021-06-03 16:49 UTC, mcolombo87 requested changes

2021-06-03 16:49 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Information/index.tsx
> +          <GradientButton text={'RENT'} />
GradientButton is not a button.

2021-06-03 19:34 UTC, CristianRWolox commented on wbooks/src/app/screens/BookDetail/components/Information/index.tsx
> +          <GradientButton text={'RENT'} />
Understood

2021-06-04 16:09 UTC, guidoprinc approved these changes

2021-06-09 17:24 UTC, mcolombo87 approved these changes

2021-06-09 17:46 UTC, merged