Card 7.1
wolox-training/cr-react-native pull request #4
Opened 2021-05-17 00:30 UTC by CristianRWolox

## Summary

- React Navigation was added.
- Navigation between book list and book detail.

## Screenshots

### Android

#### Galaxy S (or similar)
![image](https://user-images.githubusercontent.com/83975070/118413841-fba8df80-b666-11eb-86ec-9ee662faf995.png)

#### Pixel 2/3 (or similar)
![image](https://user-images.githubusercontent.com/83975070/118413844-ffd4fd00-b666-11eb-9998-f135bab7f3dc.png)

#### Pixel 3XL (or similar)
![image](https://user-images.githubusercontent.com/83975070/118413858-0a8f9200-b667-11eb-97b9-61443eaae652.png)

### iOS

#### iPhone SE (or similar)
![image](https://user-images.githubusercontent.com/83975070/118418069-8811cd00-b67c-11eb-90dd-7eeb0d6b2bdd.png)

#### iPhone 6/7/8 (or similar)
![image](https://user-images.githubusercontent.com/83975070/118418128-c4ddc400-b67c-11eb-89f2-8733b8f996ef.png)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
![image](https://user-images.githubusercontent.com/83975070/118418011-45e88b80-b67c-11eb-8331-e54f7ad8b544.png)

## Trello Card

https://trello.com/c/cwSXzyA1/13-n-71-introducci%C3%B3n-a-react-navigation

2021-05-17 14:51 UTC, mcolombo87 reviewed
The "into <Branch>" must be bookList. I can see changes in this PR that aren't of this card.

2021-05-18 14:39 UTC, guidoprinc requested changes

2021-05-18 14:39 UTC, guidoprinc commented on wbooks/src/app/screens/Library/components/BookData/index.tsx
> +      onPress={() =>
extract outside return as a `const` arrow function. Inside BookData

2021-05-18 14:39 UTC, guidoprinc commented on wbooks/src/app/screens/Library/index.tsx
> +      <FlatList data={BOOKS_MOCK} renderItem={renderItem} keyExtractor={item => item.id.toString()} />
extract keyExtractor as renderItem

2021-05-18 15:34 UTC, guidoprinc approved these changes

2021-05-18 15:45 UTC, merged