Table of comments
wolox-training/cr-react-native pull request #6
Opened 2021-05-17 04:30 UTC by CristianRWolox

## Summary

- Add table of comments to book details screen.

## Screenshots

### Android

#### Galaxy S (or similar)
![image](https://user-images.githubusercontent.com/83975070/118432421-2a8e7800-b69e-11eb-9aa0-9f1e0a6438da.png)

#### Pixel 2/3 (or similar)
![image](https://user-images.githubusercontent.com/83975070/118432428-2d896880-b69e-11eb-9359-6367e8b371ad.png)

#### Pixel 3XL (or similar)
![image](https://user-images.githubusercontent.com/83975070/118431910-fbc3d200-b69c-11eb-99f0-244088f8560d.png)

### iOS

#### iPhone SE (or similar)
![simulator_screenshot_CBFAF5FC-C4D6-49F9-BD3E-4B01E99078BF](https://user-images.githubusercontent.com/83975070/118432530-72ad9a80-b69e-11eb-81e6-b785a884d17e.png)

#### iPhone 6/7/8 (or similar)
![simulator_screenshot_4E92B9CC-6EC6-496C-B5BE-956865820D6E](https://user-images.githubusercontent.com/83975070/118432591-97097700-b69e-11eb-80c3-e2063596ba98.png)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
![image](https://user-images.githubusercontent.com/83975070/118432514-6aedf600-b69e-11eb-873f-61ab46714c3c.png)

## Trello Card

https://trello.com/c/eB3O2GGL/16-n-73-tabla-de-comentarios

2021-05-17 14:52 UTC, mcolombo87 reviewed
The "into <Branch>" must be **bookDetail**. I can see changes in this PR that aren't of this card.

2021-05-19 14:10 UTC, mcolombo87 requested changes

2021-05-19 14:10 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
Think of this as information provided by a backend service. This does not scale. Use a flat list and set a "Comment" component as the item to render. If you received 10 comments from the backend, this view doesn't even have a scroll.

2021-05-19 14:10 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +import user1 from '@assets/General/img_user1.png';
This must be inside of the "comment" mock. Is information provided by a service (We are mocking that data really, but think it like that)

2021-05-19 14:14 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
Ok, I see the scroll in Book Detail but I don't think if this is the best approach. If you want the scroll in the father don´t use the flatlist but this map is not the best. You can use a flat with a header, I will try this of another way... what do you think?

2021-05-19 15:19 UTC, CristianRWolox commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
My idea is to use ScrollView - map, I thought of using flatlist but I think is an error put a FlatList inside a parent Scroll.

It's not clear for me the 'flat with a header'

What can I do about the flatlist, put it on the child and the parent with scroll?

2021-05-19 15:21 UTC, CristianRWolox commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +import user1 from '@assets/General/img_user1.png';
Sorry is not clear for me, What must be inside?

2021-05-19 15:52 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
Use the scrollview or the flatlist, no both. But really really i don't like this approach. The flatlist have optimization and was builded it for this situations, i think is the better option. You can scroll only the comments if you consider that as an issue or use ListHeaderComponent and get the same behavior.

2021-05-19 15:53 UTC, mcolombo87 commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +import user1 from '@assets/General/img_user1.png';
the mock data perhaps need an item like "userImage" and get that data from there.

2021-05-19 16:04 UTC, guidoprinc commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +import user1 from '@assets/General/img_user1.png';
what he is saying that you should move this inside `mockComments` so when you get the real pictures, we will use only those

2021-05-19 16:04 UTC, guidoprinc commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
https://javascript.plainenglish.io/how-to-fix-virtualizedlists-should-never-be-nested-inside-plain-scrollviews-warning-3a2a887b4ea0

Check this post so you can add the information as the header and the comments as the real data so we avoid using a ScrollView and a FlatList

2021-05-19 17:09 UTC, CristianRWolox commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +import user1 from '@assets/General/img_user1.png';
Done!

2021-05-19 21:30 UTC, CristianRWolox commented on wbooks/src/app/screens/BookDetail/components/Comments/index.tsx
> +      {COMMENTS_MOCK.filter(comment => (viewAll ? true : comment.id < 2)).map(comment => (
Done!

2021-05-20 01:37 UTC, guidoprinc approved these changes

2021-05-21 15:38 UTC, mcolombo87 approved these changes

2021-05-21 15:45 UTC, merged